services:
  urlshortener.httpapi:
    image: ${DOCKER_REGISTRY-}urlshortenerhttpapi
    container_name: urlshortener.api
    build:
      context: .
      dockerfile: UrlShortener.HttpApi/Dockerfile
    environment:
      server: "MSI.database"
      port: "1433"
      database: "LocalDb"
      dbuser: "testUser"
      password: "testUser"
    ports:
        - "5000:5000"
        - "5001:5001"

  MSI.database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: urlshortener.database
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "testUser"
        MSSQL_ID: Developer
    ports:
        - 1433:1433